# Generated by Django 4.1.2 on 2022-10-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
