# Generated by Django 4.1.2 on 2022-10-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0003_openports_usedports_remove_user_ip_usedinstance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinstance',
            name='port',
        ),
        migrations.RemoveField(
            model_name='openinstance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usedinstance',
            name='port',
        ),
        migrations.RemoveField(
            model_name='usedinstance',
            name='user',
        ),
        migrations.AddField(
            model_name='openinstance',
            name='machine',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='usedinstance',
            name='machine',
            field=models.BinaryField(null=True),
        ),
    ]
