# Generated by Django 4.1.2 on 2022-10-21 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0004_remove_openinstance_port_remove_openinstance_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinstance',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='openinstance',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='usedinstance',
            name='machine',
        ),
        migrations.AddField(
            model_name='openinstance',
            name='instance_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='openinstance',
            name='port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aws.usedports'),
        ),
        migrations.AddField(
            model_name='usedinstance',
            name='instance_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usedinstance',
            name='port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aws.usedports'),
        ),
        migrations.AlterField(
            model_name='openinstance',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usedinstance',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
