# Generated by Django 4.1.2 on 2022-10-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0005_remove_openinstance_ip_remove_openinstance_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinstance',
            name='sg_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usedinstance',
            name='sg_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
